version: '3.8'

services:
  php:
    build: .
    container_name: lab6_php
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:9000"
    depends_on:
      - redis
      - webdis

  nginx:
    image: nginx:alpine
    container_name: lab6_nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www/html
    depends_on:
      - php

  redis:
    image: redis:7-alpine
    container_name: lab6_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  webdis:
    image: nicolas/webdis
    container_name: lab6_webdis
    ports:
      - "7379:7379"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

volumes:
  redis_data: